@extends('layouts.app')

@section('seo')
    <x-seo title="Subscription Agreement | EquipDash" description="Read the EquipDash Subscription Agreement governing the use of the EquipDash platform and services." />
@endsection

@section('content')
    <section style="padding:120px 0 80px;">
        <div class="container" style="max-width:800px;">
            <h1 class="hero-heading" style="font-size:36px;line-height:42px;margin-bottom:16px;">Subscription Agreement</h1>
            <p style="color:#828B9C;margin-bottom:8px;">Effective Date: February 22, 2026</p>
            <p style="color:#828B9C;margin-bottom:32px;font-size:15px;line-height:22px;">
                <strong>EquipDash Software LLC</strong><br>
                1021 E Lincolnway Suite #9844, Cheyenne, Wyoming 82001<br>
                Website: equipdash.com<br>
                Contact: <a href="mailto:support@equipdash.com" style="color:#F7581F;">support@equipdash.com</a>
            </p>

            <div class="legal-content">
                <p>This Subscription Agreement ("Agreement") contains the terms and conditions governing your access to and use of the EquipDash platform and related services. Please read carefully before subscribing.</p>

                <h2>1. Definitions</h2>
                <p>In this Agreement, the following terms have the meanings set out below:</p>
                <ul>
                    <li><strong>"Agreement"</strong> means these terms and conditions, together with any Order Form, the Privacy Policy at equipdash.com/privacy, and the Data Processing Addendum (Schedule 1).</li>
                    <li><strong>"Authorized Users"</strong> means Customer's employees, contractors, and agents who are authorized by Customer to access and use the Service on Customer's behalf, subject to Plan limits.</li>
                    <li><strong>"Customer"</strong> and <strong>"you"</strong> means the business entity that has subscribed (or is evaluating) the Service. If subscribing on behalf of an organization, the individual accepts these terms on the organization's behalf.</li>
                    <li><strong>"Customer Data"</strong> means any data, content, or information submitted, uploaded, or generated by Customer or its Authorized Users through the Service, including bookings, inventory records, staff information, and operational data.</li>
                    <li><strong>"End-User"</strong> means Customer's customers or clients who interact with the Service to make bookings, sign waivers, view inventory, or complete transactions (e.g., rental customers, tour guests).</li>
                    <li><strong>"End-User Data"</strong> means personal data of End-Users processed through the Service, including names, contact details, booking preferences, and waiver signatures.</li>
                    <li><strong>"Dash AI"</strong> means EquipDash's built-in artificial intelligence assistant feature that provides automated recommendations, scheduling optimization, and operational insights.</li>
                    <li><strong>"Documentation"</strong> means the user guides, help articles, tutorials, and technical documentation available at equipdash.com/docs or within the Service.</li>
                    <li><strong>"Fee(s)"</strong> means the subscription fees and platform fees charged for use of the Service, as detailed on the pricing page at equipdash.com/pricing.</li>
                    <li><strong>"Free Trial"</strong> means the initial 21-day trial period allowing full access to the Service without charge and without requiring a payment method.</li>
                    <li><strong>"Order"</strong> means the online subscription form or process through which Customer selects a Plan, billing cycle, and accepts these terms.</li>
                    <li><strong>"Plan"</strong> means one of the following service tiers: (i) Starter at $29/month; (ii) Growth at $69/month; or (iii) Pro at $149/month, each with annual pricing at 20% discount. Plans are described on the Pricing page.</li>
                    <li><strong>"Platform Fee"</strong> means the per-booking percentage fee collected by Stripe on behalf of EquipDash at the point of each transaction, calculated as: 3% for Starter, 2% for Growth, or 1.5% for Pro. Platform Fees are separate from and in addition to any processing fees charged by Stripe.</li>
                    <li><strong>"Service"</strong> means the EquipDash platform, website, mobile applications, APIs, features, and functionality, including Dash AI, made available to Customer.</li>
                    <li><strong>"Subscription Term"</strong> means the initial billing period (monthly or annual) for which Customer has subscribed, plus any renewal periods.</li>
                </ul>

                <h2>2. Account Registration and Free Trial</h2>
                <ol>
                    <li><strong>Registration and Acceptance.</strong> By checking the "I agree" checkbox during account creation and completing the registration process, you accept and agree to be bound by this Agreement. No physical or electronic signature is required. You must provide accurate, complete, and current business information. The person registering represents and warrants that they have the authority to bind the organization to this Agreement.</li>
                    <li><strong>Free Trial Access.</strong> EquipDash provides a 21-day free trial of the Service ("Free Trial"). During the Free Trial, you have full access to all Service features with no requirement to provide payment information. You may create one Free Trial account per organization.</li>
                    <li><strong>Free Trial Terms.</strong> The Free Trial is governed by this Agreement. EquipDash may modify, suspend, or discontinue the Free Trial at any time without liability.</li>
                    <li><strong>End of Free Trial.</strong> At the conclusion of the 21-day Free Trial period, your account will automatically deactivate unless you convert to a paid Plan by selecting a subscription option and completing payment through the Order process.</li>
                    <li><strong>One Trial Per Organization.</strong> Only one Free Trial account is permitted per organization. Circumventing this limit may result in account termination.</li>
                </ol>

                <h2>3. The Service</h2>

                <h3>A. Grant of License</h3>
                <ol>
                    <li>Subject to your compliance with this Agreement, EquipDash grants you a non-exclusive, non-transferable, non-sublicensable license to access and use the Service during the Subscription Term for your internal business operations. This license is limited by the Plan you have selected.</li>
                    <li>You may not: (a) use the Service for any purpose other than your internal operations; (b) attempt to build a competing product using data or insights derived from the Service; or (c) transfer this license to any third party.</li>
                </ol>

                <h3>B. Authorized Users</h3>
                <ol>
                    <li>You may grant Authorized Users access to the Service up to the user limits specified for your Plan. You are responsible for all actions and omissions of Authorized Users, including their compliance with this Agreement.</li>
                    <li>You must ensure that each Authorized User agrees to be bound by this Agreement and any acceptable use policies.</li>
                </ol>

                <h3>C. Service Availability</h3>
                <ol>
                    <li>EquipDash uses commercially reasonable efforts to maintain continuous availability of the Service. We perform scheduled maintenance as needed and will endeavor to conduct maintenance outside of normal business hours with reasonable advance notice.</li>
                    <li>The Service is not subject to a service level agreement (SLA) or guaranteed uptime percentage. Planned and emergency maintenance may result in temporary unavailability.</li>
                </ol>

                <h3>D. Service Modifications</h3>
                <ol>
                    <li>EquipDash may update, modify, enhance, or add features to the Service at any time. We will provide 30 days' advance written notice if a modification materially reduces the core functionality of your current Plan.</li>
                    <li>You may terminate this Agreement if material changes significantly impair the Service's core function, provided you notify EquipDash within 30 days of the notice.</li>
                </ol>

                <h3>E. Dash AI</h3>
                <ol>
                    <li>Dash AI is an AI-powered assistant that processes your Customer Data and End-User Data to provide automated operations, insights, recommendations, and task automation.</li>
                    <li><strong>AI Output Disclaimer.</strong> Dash AI outputs are provided on an "as is" basis. EquipDash does not guarantee the accuracy, completeness, or appropriateness of AI-generated recommendations or insights. You should not rely solely on Dash AI output for business-critical decisions without independent verification.</li>
                    <li><strong>Usage Limits.</strong> Dash AI features are subject to token and usage limits that vary by Plan. EquipDash may modify these limits with reasonable notice.</li>
                    <li><strong>Data Processing.</strong> When you use Dash AI, Customer Data and End-User Data are processed to generate recommendations and insights. Processing is governed by the Data Processing Addendum in Schedule 1.</li>
                </ol>

                <h3>F. API Access</h3>
                <ol>
                    <li>API access is available exclusively for Pro plan subscribers. API use is subject to rate limits, usage quotas, and acceptable use requirements outlined in the API Documentation.</li>
                    <li>EquipDash may modify, disable, or deprecate APIs with reasonable advance notice. EquipDash is not liable for any disruption to API services.</li>
                </ol>

                <h2>4. Customer Responsibilities</h2>
                <ol>
                    <li><strong>Legal Compliance.</strong> You are responsible for ensuring that your use of the Service and processing of all data complies with applicable laws and regulations, including data protection laws, payment processing laws, and any industry-specific regulations relevant to your business.</li>
                    <li><strong>Customer Data Responsibility.</strong> You represent that you own or have the right to provide all Customer Data to EquipDash. You are responsible for the legality, accuracy, and appropriateness of all Customer Data.</li>
                    <li><strong>End-User Consents.</strong> You must obtain all necessary consents from End-Users before collecting, processing, or transmitting their personal data through the Service. You are responsible for providing privacy notices and obtaining required waivers and acknowledgments.</li>
                    <li><strong>Prohibited Data.</strong> You must not upload or transmit Sensitive Data, including: social security numbers, health records, financial account numbers or credit card numbers (except through Stripe payment processing), government identification numbers, or biometric data.</li>
                    <li><strong>Authorized User Management.</strong> You are responsible for managing Authorized User access, ensuring compliance, and maintaining the security of user credentials. You must remove users who no longer require access.</li>
                    <li><strong>Prohibited Conduct.</strong> You must not:
                        <ul>
                            <li>Reverse engineer, decompile, or attempt to derive the source code of the Service</li>
                            <li>Sublicense, resell, time-share, or lease the Service to third parties</li>
                            <li>Use the Service to develop a competing product or service</li>
                            <li>Exceed the user, storage, API call, or transaction limits specified for your Plan</li>
                            <li>Transmit viruses, malware, or harmful code</li>
                            <li>Attempt to gain unauthorized access to the Service or its systems</li>
                            <li>Circumvent security measures or acceptable use policies</li>
                            <li>Use the Service for illegal activities or to harm others</li>
                        </ul>
                    </li>
                    <li><strong>Account Security.</strong> You must maintain the confidentiality of your account credentials and are responsible for all activity under your account. Notify EquipDash immediately of unauthorized access.</li>
                </ol>

                <h2>5. Fees and Payment</h2>

                <h3>A. Subscription Fees</h3>
                <ol>
                    <li>Subscription fees are charged in advance on a monthly or annual basis, depending on your selection during the Order process. Pricing for each Plan is available at equipdash.com/pricing.</li>
                    <li>Annual subscriptions are charged at a 20% discount compared to monthly pricing.</li>
                    <li>Charges are automatically renewed at the end of each billing period unless you cancel before the renewal date.</li>
                </ol>

                <h3>B. Platform Fees</h3>
                <ol>
                    <li>In addition to subscription fees, a Platform Fee is collected by Stripe at the point of each booking transaction and remitted to EquipDash automatically. The Platform Fee percentage is determined by your Plan:
                        <ul>
                            <li>Starter Plan: 3% per booking</li>
                            <li>Growth Plan: 2% per booking</li>
                            <li>Pro Plan: 1.5% per booking</li>
                        </ul>
                    </li>
                    <li>Platform Fees are calculated on the gross transaction value of each booking processed through the Service. You may configure your account to either absorb the Platform Fee or pass it on to your End-Users at checkout. Regardless of this setting, EquipDash receives the Platform Fee from Stripe at the time of the transaction.</li>
                    <li>Platform Fees are collected in real time by Stripe at the point of each transaction. Stripe may also charge its own separate payment processing fees (e.g., Stripe's standard per-transaction rate), which are between you and Stripe and are not set or controlled by EquipDash. You are responsible for reviewing and agreeing to Stripe's terms and fee schedule.</li>
                </ol>

                <h3>C. Payment Method and Processing</h3>
                <ol>
                    <li>All payments are processed through Stripe. By submitting payment information, you authorize EquipDash to charge your payment method for subscription fees and authorize Stripe to collect Platform Fees at the point of each booking transaction on EquipDash's behalf. Your use of Stripe is subject to Stripe's own terms of service and privacy policy.</li>
                    <li>You are responsible for maintaining accurate payment information. If a payment fails, EquipDash will attempt to charge again.</li>
                    <li><strong>Failed Payment Procedure.</strong> If a payment fails, EquipDash will notify you. You have 7 days to update your payment method. If not resolved within 7 days, EquipDash may suspend your access to the Service.</li>
                </ol>

                <h3>D. Price Changes</h3>
                <ol>
                    <li>EquipDash may change subscription or Platform Fees with 30 days' advance written notice via email.</li>
                    <li>Price changes take effect at your next billing cycle renewal. If you do not agree with a price increase, you may cancel within the 30-day notice period without penalty.</li>
                </ol>

                <h3>E. Taxes</h3>
                <p>All Fees quoted are exclusive of sales tax, VAT, or other applicable taxes. You are responsible for any taxes on your purchases (EquipDash is responsible only for its own income tax obligations).</p>

                <h3>F. No Refunds</h3>
                <ol>
                    <li>All Fees are non-refundable once charged. This applies regardless of whether you use the Service during the billing period or only partially complete a billing cycle.</li>
                    <li>If you cancel mid-month, you will not receive a refund for the unused portion of your subscription.</li>
                </ol>

                <h3>G. Plan Changes</h3>
                <ol>
                    <li><strong>Upgrades.</strong> Upgrading to a higher-tier Plan takes effect immediately. You will be charged the difference between your current Plan and the new Plan on a prorated basis.</li>
                    <li><strong>Downgrades.</strong> Downgrading to a lower-tier Plan takes effect at the next billing cycle renewal. Note that downgrading may result in loss of features or data that exceeds the limits of your new Plan.</li>
                </ol>

                <h3>H. Late Payment</h3>
                <p>If a fee payment is overdue, EquipDash may charge interest at 1.5% per month on the outstanding balance (or at the maximum legal interest rate, whichever is lower).</p>

                <h2>6. Intellectual Property</h2>

                <h3>A. EquipDash Intellectual Property</h3>
                <p>EquipDash retains all right, title, and interest in and to: (a) the Service, including all software, algorithms, and code; (b) the Documentation; (c) Dash AI and all AI models and training data; (d) all EquipDash trademarks, logos, and brand materials; (e) all improvements, modifications, and derivative works created by EquipDash. No ownership rights in the Service transfer to you. Your license is limited to the right to use the Service as permitted under Section 3.A.</p>

                <h3>B. Customer Data Rights</h3>
                <ol>
                    <li>You retain all right, title, and interest in Customer Data. By uploading Customer Data to the Service, you grant EquipDash a limited license to process, store, and use Customer Data solely to provide and improve the Service.</li>
                    <li>This license includes the right for EquipDash to: (a) store and maintain Customer Data on secure servers; (b) use Customer Data as input to Dash AI to provide recommendations; (c) process Customer Data as required for Service functionality.</li>
                </ol>

                <h3>C. Feedback</h3>
                <p>Any feedback, suggestions, ideas, or comments you provide to EquipDash regarding the Service will be treated as non-confidential and may be used by EquipDash royalty-free for any purpose, including product development.</p>

                <h3>D. Aggregated and Anonymized Data</h3>
                <ol>
                    <li>EquipDash may collect, analyze, and use anonymized, aggregated data derived from use of the Service for analytics, benchmarking, product improvement, and research purposes. This data will not identify you or any End-User and will be treated as EquipDash's property.</li>
                    <li>Examples include aggregate booking trends, feature usage statistics, and platform-wide performance metrics.</li>
                </ol>

                <h2>7. Confidentiality</h2>
                <ol>
                    <li><strong>Definition.</strong> "Confidential Information" means any proprietary information disclosed by one party to the other, including business data, technical information, financial information, pricing, and the terms of this Agreement.</li>
                    <li><strong>Confidentiality Obligations.</strong> Each party will: (a) maintain Confidential Information in strict confidence; (b) protect it using at least the same degree of care applied to its own confidential information; (c) limit access to employees and contractors with a need to know; (d) not disclose Confidential Information to third parties without prior written consent.</li>
                    <li><strong>Exclusions.</strong> Confidentiality obligations do not apply to information that: (a) was publicly known or becomes publicly known through no breach by the recipient; (b) was rightfully received by the recipient from a third party without confidentiality obligations; (c) was independently developed without reference to the Confidential Information; (d) was required to be disclosed by law or court order.</li>
                    <li><strong>Required Disclosure.</strong> If a party is required by law, subpoena, or court order to disclose Confidential Information, it will notify the other party promptly (if legally permitted) so the other party may seek protective measures.</li>
                    <li><strong>Term.</strong> Confidentiality obligations survive termination of this Agreement for 3 years from the date of disclosure. Trade secrets will be protected indefinitely.</li>
                </ol>

                <h2>8. Data Protection and Privacy</h2>
                <ol>
                    <li><strong>Data Processing Roles.</strong> EquipDash processes Customer Data and End-User Data on your behalf as a data processor. You are the data controller. This means you determine the purposes and means of processing, and EquipDash processes data only on your instructions.</li>
                    <li><strong>Privacy Policy.</strong> EquipDash's <a href="/privacy-policy">Privacy Policy</a> describes how EquipDash collects, uses, and protects personal data for the website and related services. Processing of Customer Data and End-User Data is governed by this Agreement and the Data Processing Addendum (Schedule 1).</li>
                    <li><strong>Your Data Protection Obligations.</strong> You must:
                        <ul>
                            <li>Determine a lawful basis for processing End-User Data under applicable data protection laws</li>
                            <li>Provide End-Users with privacy notices disclosing data processing and use of the Service</li>
                            <li>Obtain necessary consents or approvals for processing End-User personal data</li>
                            <li>Comply with End-User requests for access, rectification, or deletion of their data</li>
                            <li>Respond to data subject requests and forward EquipDash any requests for assistance</li>
                        </ul>
                    </li>
                    <li><strong>Data Processing Addendum.</strong> The DPA in Schedule 1 governs all processing of personal data and is an integral part of this Agreement. In case of conflict, the DPA controls regarding data processing.</li>
                    <li><strong>Sub-processors.</strong> EquipDash uses third-party sub-processors (such as AWS for hosting). You authorize EquipDash to engage sub-processors. EquipDash will notify you 30 days before adding new sub-processors, and you may object within 30 days if you have concerns.</li>
                    <li><strong>Data Location.</strong> All Customer Data and End-User Data are stored and processed in the United States on AWS infrastructure. If you have requirements for data residency in other locations, you must notify EquipDash before subscribing.</li>
                    <li><strong>Security.</strong> EquipDash implements commercially reasonable technical and organizational security measures to protect personal data, including encryption, access controls, and regular security testing. Further details are in the DPA (Schedule 1).</li>
                </ol>

                <h2>9. Term and Termination</h2>

                <h3>A. Subscription Term and Renewal</h3>
                <ol>
                    <li>Your Subscription Term begins on the first day you complete payment for your chosen Plan. The initial term is one month or one year, depending on your billing cycle selection.</li>
                    <li><strong>Automatic Renewal.</strong> Your subscription automatically renews for successive periods unless you cancel before the renewal date. Charges for renewal will be made using your payment method on file.</li>
                </ol>

                <h3>B. Termination by Customer</h3>
                <ol>
                    <li>You may cancel your subscription at any time. Cancellation can be initiated through your account settings or by emailing <a href="mailto:support@equipdash.com">support@equipdash.com</a>.</li>
                    <li>Cancellation becomes effective at the end of your current billing period. You will not be refunded for any unused portion of your current billing cycle.</li>
                </ol>

                <h3>C. Termination by EquipDash for Cause</h3>
                <p>EquipDash may terminate this Agreement for cause under the following circumstances:</p>
                <ul>
                    <li><strong>Material Breach.</strong> You materially breach this Agreement and fail to cure the breach within 30 days of receiving written notice from EquipDash.</li>
                    <li><strong>Non-Payment.</strong> You fail to pay fees within 7 days of notice of failed payment.</li>
                    <li><strong>Prohibited Conduct.</strong> You violate Section 4.6 (prohibited conduct) or engage in unacceptable use that harms the Service or other users.</li>
                    <li><strong>Insolvency.</strong> You become insolvent, bankrupt, enter receivership, or cease operations.</li>
                </ul>
                <p>Termination for cause will result in immediate cessation of your access to the Service.</p>

                <h3>D. Termination by EquipDash Without Cause</h3>
                <ol>
                    <li>EquipDash may terminate this Agreement without cause by providing you 90 days' advance written notice.</li>
                    <li>Upon termination without cause, EquipDash will provide you with a pro-rata refund of any prepaid fees for the unused portion of your subscription.</li>
                </ol>

                <h3>E. Effect of Termination</h3>
                <ol>
                    <li>Immediately upon termination, your access to the Service will cease. You will not be able to log in or use Service features.</li>
                    <li><strong>Data Retention.</strong> You have 30 days following termination to export your Customer Data. After the 30-day period, EquipDash will permanently delete all of your Customer Data from its servers. No recovery is possible after deletion.</li>
                    <li><strong>Surviving Obligations.</strong> Sections pertaining to intellectual property, confidentiality, liability limitations, indemnification, and data protection will survive termination.</li>
                </ol>

                <h3>F. Suspension</h3>
                <p>EquipDash may temporarily suspend your access to the Service (without terminating this Agreement) if:</p>
                <ul>
                    <li>Required by law or government order</li>
                    <li>Necessary to prevent imminent security threats or violation of the law</li>
                    <li>You are in material breach of this Agreement and EquipDash has provided notice of the breach</li>
                </ul>
                <p>EquipDash will provide notice of suspension when reasonably practicable. Upon resolution of the underlying issue, access will be restored.</p>

                <h2>10. Warranties and Disclaimers</h2>

                <h3>A. EquipDash Warranties</h3>
                <p>EquipDash warrants that: (a) the Service will substantially conform to the Documentation; (b) the Service will comply with applicable laws; (c) EquipDash will not knowingly introduce malware or harmful code into the Service.</p>

                <h3>B. Customer Warranties</h3>
                <p>You warrant that: (a) you have the authority to enter into this Agreement; (b) you will comply with applicable laws; (c) you own or have the right to provide all Customer Data; (d) you have obtained necessary consents from End-Users for data processing through the Service.</p>

                <h3>C. Disclaimer of All Other Warranties</h3>
                <p><strong>EXCEPT AS EXPRESSLY STATED IN SECTION A ABOVE, THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. EQUIPDASH DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.</strong></p>
                <p><strong>EQUIPDASH DOES NOT WARRANT THAT: (a) THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; (b) DEFECTS WILL BE CORRECTED; (c) THE SERVICE WILL MEET YOUR REQUIREMENTS.</strong></p>
                <p><strong>DASH AI OUTPUTS ARE PROVIDED ON AN "AS IS" BASIS. EQUIPDASH DOES NOT GUARANTEE THE ACCURACY, COMPLETENESS, RELIABILITY, OR APPROPRIATENESS OF AI-GENERATED CONTENT. YOU SHOULD NOT RELY SOLELY ON DASH AI RECOMMENDATIONS FOR BUSINESS-CRITICAL DECISIONS.</strong></p>

                <h2>11. Limitation of Liability</h2>

                <h3>A. Exclusion of Consequential Damages</h3>
                <p><strong>NEITHER PARTY SHALL BE LIABLE TO THE OTHER FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST REVENUE, LOSS OF DATA, LOSS OF BUSINESS OPPORTUNITY, OR LOSS OF USE, REGARDLESS OF THE CAUSE AND WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</strong></p>

                <h3>B. Liability Cap</h3>
                <p><strong>EQUIPDASH'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, THE SERVICE, CUSTOMER DATA, OR ANY OTHER MATTER SHALL NOT EXCEED THE TOTAL FEES PAID BY CUSTOMER IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO LIABILITY. IF NO FEES HAVE BEEN PAID OR THE CUSTOMER IS ON A FREE TRIAL, LIABILITY IS LIMITED TO $100.</strong></p>

                <h3>C. Exceptions to Limitations</h3>
                <p>The limitations in Sections A and B do not apply to: (a) Customer's payment obligations under this Agreement; (b) either party's indemnification obligations; (c) breach of confidentiality obligations; (d) willful misconduct or gross negligence.</p>

                <h2>12. Indemnification</h2>
                <p>Customer indemnification obligations and EquipDash indemnification obligations are detailed in this section. Each party will indemnify the other against third-party claims arising from breaches of this Agreement or violations of applicable laws.</p>

                <h2>13. Governing Law and Dispute Resolution</h2>
                <p>This Agreement is governed by and construed in accordance with the laws of the State of Wyoming, without regard to its conflicts of law principles.</p>
                <p>Any dispute arising out of or relating to this Agreement shall be resolved by binding arbitration under the Commercial Arbitration Rules of the American Arbitration Association (AAA) in Cheyenne, Wyoming.</p>
                <p><strong>YOU AND EQUIPDASH AGREE THAT ANY DISPUTE MUST BE BROUGHT ON AN INDIVIDUAL BASIS. YOU WAIVE THE RIGHT TO PARTICIPATE IN CLASS ACTION, CLASS ARBITRATION, CONSOLIDATED PROCEEDINGS, OR REPRESENTATIVE ACTIONS AGAINST EQUIPDASH.</strong></p>

                <h2>14. General Provisions</h2>
                <ol>
                    <li><strong>Entire Agreement.</strong> This Agreement, including the <a href="/privacy-policy">Privacy Policy</a> and the Data Processing Addendum (Schedule 1), constitutes the entire agreement between you and EquipDash regarding the Service.</li>
                    <li><strong>Amendment and Updates.</strong> EquipDash may modify these terms and conditions at any time. Material modifications will be provided with 30 days' advance notice via email.</li>
                    <li><strong>Assignment.</strong> You may not assign this Agreement without EquipDash's prior written consent, except in connection with a merger, acquisition, or sale of substantially all of your assets.</li>
                    <li><strong>Severability.</strong> If any provision of this Agreement is held invalid, illegal, or unenforceable, that provision will be modified or severed while the remaining provisions remain in full force.</li>
                    <li><strong>Force Majeure.</strong> Neither party will be liable for failure to perform due to causes beyond its reasonable control, except payment obligations are not excused.</li>
                </ol>

                <h2>Schedule 1: Data Processing Addendum (DPA)</h2>
                <p>This Data Processing Addendum (DPA) is an integral part of the Subscription Agreement and governs the processing of personal data by EquipDash on behalf of Customer.</p>

                <h3>Part 1: Scope and Applicability</h3>
                <ol>
                    <li>This DPA applies to any processing of personal data (as defined under GDPR and other applicable data protection laws) that EquipDash undertakes on behalf of Customer in connection with the Service.</li>
                    <li><strong>Scope.</strong> This DPA covers processing of personal data in Customer Data and End-User Data for the purpose of providing the Service.</li>
                </ol>

                <h3>Part 2: Data Processing Roles</h3>
                <ol>
                    <li>Customer is the data controller, determining the purposes and means of processing.</li>
                    <li>EquipDash is the data processor, processing personal data only on Customer's documented instructions.</li>
                </ol>

                <h3>Part 3: Scope of Processing</h3>
                <ol>
                    <li><strong>Subject Matter.</strong> Processing personal data to provide the EquipDash Service, including booking management, customer management, staff scheduling, and AI-powered automation.</li>
                    <li><strong>Duration.</strong> For the Subscription Term plus a 30-day wind-down period following termination.</li>
                    <li><strong>Data Subjects.</strong> End-Users and Authorized Users.</li>
                </ol>

                <h3>Part 4: Security Measures</h3>
                <p>EquipDash implements: (a) Encryption at rest using AES-256; (b) Encryption in transit using TLS 1.2+; (c) Access controls; (d) Multi-factor authentication; (e) Regular security testing; (f) Incident response procedures.</p>

                <h3>Part 5: Sub-Processors</h3>
                <ol>
                    <li>Customer authorizes EquipDash to engage sub-processors. Current sub-processors: Amazon Web Services (AWS), Stripe, and other service providers listed at equipdash.com/sub-processors.</li>
                    <li>EquipDash will notify Customer 30 days before engaging new sub-processors.</li>
                </ol>

                <h3>Part 6: Data Breach Notification</h3>
                <p>Upon discovering a security breach, EquipDash will notify Customer without undue delay and, where possible, within 72 hours.</p>

                <h3>Part 7: Data Location</h3>
                <p>All personal data is processed, stored, and backed up exclusively in the United States on AWS infrastructure.</p>

                <h2>Acceptance</h2>
                <p>This Agreement does not require a physical or electronic signature. By checking the "I agree to the Subscription Agreement, Privacy Policy, and Terms of Use" checkbox during account creation and clicking the account creation button, you acknowledge that you have read, understood, and agree to be bound by this Agreement in its entirety.</p>
                <p>If you are accepting this Agreement on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these terms. In that case, "Customer" and "you" refer to that organization.</p>
                <p>The date on which you first check the acceptance box and create your account is the effective date of this Agreement.</p>

                <p style="margin-top:32px;">
                    <strong>EquipDash Software LLC</strong><br>
                    1021 E Lincolnway Suite #9844<br>
                    Cheyenne, Wyoming 82001, United States<br>
                    <a href="mailto:support@equipdash.com">support@equipdash.com</a>
                </p>
            </div>
        </div>
    </section>
@endsection
